name: Test Docker Build and Push

on: push
env:
  IMAGE_NAME: burninmedia/actionsci
  VERSION: 0.1.0-test
  DIRECTORY: .
  DOCKERFILE: ./Dockerfile
  BUILD_ARGS: ''
  REGISTRY_URL: docker.io
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
      # read thhe action.yaml file and then executing the value found in the action.yaml runs.steps.*. use yq to get value from yaml file
      - name: Extract run command from action.yml
        id: extract_run
        run: |
          run_command=$(yq eval '.runs.steps[].run' action.yml)
          echo "run_command<<EOF" >> $GITHUB_ENV
          echo "$run_command" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Simulate running the extracted run command
        run: |
          # Load the run command from the environment variable
          run_command="${{ env.run_command }}"
          
          # Assuming your environment variables are correctly set up
          # Simulate the execution of the run command
          echo "Simulating the execution of the run command:"
          echo "$run_command"
      #Step that will delete the test image from repo using bash commands if previous step is successful
      - name: Delete test image from Docker Hub
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKER_HUB_USERNAME }}'", "password": "'${{ secrets.DOCKER_HUB_PASSWORD }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/tags/${{ env.VERSION }}
  
